name: Download Images

on:
  workflow_dispatch:
    inputs:
      start_range:
        description: "Start range (optional)"
        required: false
        type: string
      end_range:
        description: "End range (optional)"
        required: false
        type: string
  schedule:
    - cron: "0 * * * *"  # Runs at the start of every hour

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      total_end: ${{ steps.set-matrix.outputs.total_end }}
    steps:
      - name: Sparse checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          sparse-checkout: |
            range.json
            .github/workflows/download-images.yml
          sparse-checkout-cone-mode: false
          fetch-depth: 1

      - name: Load state and prepare matrix
        id: set-matrix
        run: |
          if [ -f range.json ]; then
            start=$(jq -r '.start' range.json)
            end=$(jq -r '.end' range.json)
          else
            start="${{ inputs.start_range || '1000' }}"
            end="${{ inputs.end_range || '2000' }}"
          fi
          
          # Create ranges for each letter a-z
          for letter in a b c d q r s t u; do
              ranges+=("{\"prefix\":\"$letter\",\"start\":$start,\"end\":$end}")
          done
          
          matrix=$(printf '%s\n' "${ranges[@]}" | jq -sc '{range: .}')
          echo "matrix=$matrix" >> $GITHUB_OUTPUT
          echo "total_end=$end" >> $GITHUB_OUTPUT

  download-batch:
    needs: prepare-matrix
    runs-on: ubuntu-latest
    outputs:
      has_images: ${{ steps.check-downloads.outputs.has_images }}
      start_range: ${{ matrix.range.start }}
      end_range: ${{ matrix.range.end }}
      prefix: ${{ matrix.range.prefix }}
    strategy:
      matrix: ${{ fromJson(needs.prepare-matrix.outputs.matrix) }}
      fail-fast: false
      # Reduce parallel jobs to prevent disk space issues
      max-parallel: 3
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          # Use sparse checkout to minimize disk usage
          sparse-checkout: |
            crawler_images.py
          sparse-checkout-cone-mode: false
          fetch-depth: 1
  
      - name: Clean up disk space
        run: |
          echo "Cleaning up disk space before processing..."
          df -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          df -h
  
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
  
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir requests Pillow
  
      - name: Process batch
        id: check-downloads
        run: |
          # Check available space before processing
          available_space=$(df -BM / | awk 'NR==2 {print $4}' | sed 's/M//')
          if [ "$available_space" -lt "1000" ]; then
            echo "Error: Insufficient disk space (less than 1GB available)"
            exit 1
          fi

          today=$(date +%Y%m%d)
          folder="images_${{ matrix.range.prefix }}_${today}_${{ matrix.range.start }}_to_${{ matrix.range.end }}"
          mkdir -p "$folder"
          
          echo "Processing batch: ${{ matrix.range.prefix }}${{ matrix.range.start }} to ${{ matrix.range.prefix }}${{ matrix.range.end }}"
          python crawler_images.py "${{ matrix.range.prefix }}" "${{ matrix.range.start }}" "${{ matrix.range.end }}" "$folder"
          
          # Check disk space after download
          available_space=$(df -BM / | awk 'NR==2 {print $4}' | sed 's/M//')
          if [ "$available_space" -lt "500" ]; then
            echo "Warning: Low disk space after download (less than 500MB available)"
          fi
          
          # Check if any images were downloaded
          image_count=$(find "$folder" -name "*.jpg" | wc -l)
          if [ "$image_count" -eq 0 ]; then
            echo "No images downloaded in this batch"
            echo "has_images=false" >> $GITHUB_OUTPUT
            echo "$(date '+%Y-%m-%d %H:%M:%S') - No images found in range ${{ matrix.range.start }} to ${{ matrix.range.end }} with prefix ${{ matrix.range.prefix }}" >> empty_ranges.log
          else
            echo "has_images=true" >> $GITHUB_OUTPUT
          fi
          
          echo "folder_name=$folder" >> $GITHUB_OUTPUT

      - name: Upload batch artifacts
        if: steps.check-downloads.outputs.has_images == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: batch-${{ matrix.range.prefix }}-${{ matrix.range.start }}-${{ matrix.range.end }}
          path: images_${{ matrix.range.prefix }}_*_${{ matrix.range.start }}_to_${{ matrix.range.end }}
          retention-days: 1
          # Add compression to reduce disk space usage
          compression-level: 9

      - name: Cleanup after upload
        if: always()
        run: |
          rm -rf images_*
          df -h

  commit-changes:
    needs: [prepare-matrix, download-batch]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Clean workspace before checkout
        run: |
          echo "Checking disk space..."
          df -h
          echo "Cleaning up unnecessary files..."
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          df -h

      - name: Minimal checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          sparse-checkout: |
            range.json
            empty_ranges.log
          sparse-checkout-cone-mode: false
          fetch-depth: 1

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./downloads
          merge-multiple: true

      - name: Process and commit changes in batches
        run: |
          git config user.name "${{ github.repository_owner }}"
          git config user.email "${{ github.repository_owner }}@users.noreply.github.com"

          # Create empty_ranges.log if it doesn't exist
          touch empty_ranges.log
          
          # Add empty range log if no images were found
          if [ "${{ needs.download-batch.outputs.has_images }}" = "false" ]; then
            echo "$(date '+%Y-%m-%d %H:%M:%S') - No images found in range ${{ needs.download-batch.outputs.start_range }} to ${{ needs.download-batch.outputs.end_range }} with prefix ${{ needs.download-batch.outputs.prefix }}" >> empty_ranges.log
          fi

          # Update range.json for next run
          next_start=$((${{ needs.prepare-matrix.outputs.total_end }} + 1))
          next_end=$((${{ needs.prepare-matrix.outputs.total_end }} + 501))
          echo "{\"start\": $next_start, \"end\": $next_end}" > range.json
          
          # Stage range.json and empty_ranges.log first
          git add range.json empty_ranges.log

          # Process downloaded files in smaller batches
          if [ -d "./downloads" ]; then
            cd downloads
            
            # Process files in batches of 100
            find . -type f -print0 | while IFS= read -r -d '' file; do
              # Check available space
              available_space=$(df -BM / | awk 'NR==2 {print $4}' | sed 's/M//')
              if [ "$available_space" -lt "500" ]; then
                echo "Warning: Low disk space, committing current batch..."
                cd ..
                git commit -m "chore: partial commit of downloaded images"
                git push
                cd downloads
              fi

              # Create target directory and move file
              target_dir="../$(dirname "${file#./}")"
              mkdir -p "$target_dir"
              mv "$file" "$target_dir/"
              
              # Stage the moved file
              cd ..
              git add "$target_dir/$(basename "$file")"
              cd downloads
            done
            cd ..
          fi

          # Commit any remaining changes
          if ! git diff --staged --quiet; then
            today=$(date +%Y-%m-%d)
            if [ "${{ needs.download-batch.outputs.has_images }}" = "true" ]; then
              git commit -m "chore: download images for prefix ${{ needs.download-batch.outputs.prefix }} in ${today} from ids ${next_start} to ${next_end}"
            else
              git commit -m "log: no images found in range ${{ needs.download-batch.outputs.start_range }} to ${{ needs.download-batch.outputs.end_range }}"
            fi
            git push
          fi

      - name: Cleanup
        if: always()
        run: |
          rm -rf downloads
          rm -rf .git
          df -h

      - name: Delete old artifacts
        env:
          REPO: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          echo "Fetching artifacts from repository..."
          artifacts=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" "https://api.github.com/repos/$REPO/actions/artifacts" | jq -c '.artifacts[]')

          echo "Filtering artifacts for deletion..."
          for artifact in $artifacts; do
            id=$(echo $artifact | jq -r '.id')
            name=$(echo $artifact | jq -r '.name')
            size=$(echo $artifact | jq -r '.size_in_bytes')
            updated_at=$(echo $artifact | jq -r '.updated_at')
            size_in_gb=$((size / 1024 / 1024 / 1024))

            # Check if artifact is older than 1 day or larger than 3GB
            if [[ "$(date -d "$updated_at" +%s)" -lt "$(date -d '1 day ago' +%s)" || $size_in_gb -gt 3 ]]; then
              echo "Deleting artifact: $name (ID: $id, Size: $size_in_gb GB, Updated: $updated_at)"
              curl -X DELETE -s -H "Authorization: Bearer $GITHUB_TOKEN" "https://api.github.com/repos/$REPO/actions/artifacts/$id"
            fi
          done