name: Download Images

on:
  workflow_dispatch:
    inputs:
      start_range:
        description: "Start range (optional)"
        required: false
        type: string
      end_range:
        description: "End range (optional)"
        required: false
        type: string
  schedule:
    - cron: "0 0 */2 * *"  # Runs once every 2 days

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      total_end: ${{ steps.set-matrix.outputs.total_end }}
    steps:
      - name: Sparse checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          sparse-checkout: |
            input/range.json
            .github/workflows/download-images.yml
          sparse-checkout-cone-mode: false
          fetch-depth: 1

      - name: Load state and prepare matrix
        id: set-matrix
        run: |
          if [ -f input/range.json ]; then
            start=$(jq -r '.start' input/range.json)
            end=$(jq -r '.end' input/range.json)
          else
            start="${{ inputs.start_range || '1000' }}"
            end="${{ inputs.end_range || '2000' }}"
          fi
          
          # Create ranges for each letter a-z
          for letter in {a..z}; do
              ranges+=("{\"prefix\":\"$letter\",\"start\":$start,\"end\":$end}")
          done
          
          matrix=$(printf '%s\n' "${ranges[@]}" | jq -sc '{range: .}')
          echo "matrix=$matrix" >> $GITHUB_OUTPUT
          echo "total_end=$end" >> $GITHUB_OUTPUT

  download-batch:
    needs: prepare-matrix
    runs-on: ubuntu-latest
    outputs:
      has_images: ${{ steps.check-downloads.outputs.has_images }}
      start_range: ${{ matrix.range.start }}
      end_range: ${{ matrix.range.end }}
      prefix: ${{ matrix.range.prefix }}
    strategy:
      matrix: ${{ fromJson(needs.prepare-matrix.outputs.matrix) }}
      fail-fast: false
      # Reduce parallel jobs to prevent disk space issues
      max-parallel: 3
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          # Use sparse checkout to minimize disk usage
          sparse-checkout: |
            scripts/crawler_images.py
          sparse-checkout-cone-mode: false
          fetch-depth: 1
  
      - name: Clean up disk space
        run: |
          echo "Cleaning up disk space before processing..."
          df -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          df -h
  
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
  
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir requests Pillow
  
      - name: Process batch
        id: check-downloads
        run: |
          # Add initial debug output
          echo "Starting batch processing..."
          
          # Check available space before processing
          available_space=$(df -BM / | awk 'NR==2 {print $4}' | sed 's/M//')
          echo "Available space: ${available_space}MB"
          
          if [ "$available_space" -lt "1000" ]; then
            echo "Error: Insufficient disk space (less than 1GB available)"
            exit 1
          fi

          today=$(date +%Y%m%d)
          folder="images_${{ matrix.range.prefix }}_${today}_${{ matrix.range.start }}_to_${{ matrix.range.end }}"
          mkdir -p "$folder"
          
          echo "Processing batch: ${{ matrix.range.prefix }}${{ matrix.range.start }} to ${{ matrix.range.prefix }}${{ matrix.range.end }}"
          python scripts/crawler_images.py "${{ matrix.range.prefix }}" "${{ matrix.range.start }}" "${{ matrix.range.end }}" "$folder"
          
          # Check disk space after download
          available_space=$(df -BM / | awk 'NR==2 {print $4}' | sed 's/M//')
          echo "Available space after download: ${available_space}MB"
          
          # Check if any images were downloaded
          image_count=$(find "$folder" -type f -name "*.jpg" | wc -l)
          echo "Number of images found: $image_count"
          
          if [ "$image_count" -eq 0 ]; then
            echo "No images downloaded in this batch"
            echo "has_images=false" >> "$GITHUB_OUTPUT"
            echo "$(date '+%Y-%m-%d %H:%M:%S') - No images found in range ${{ matrix.range.start }} to ${{ matrix.range.end }} with prefix ${{ matrix.range.prefix }}" >> empty_ranges.log
          else
            echo "Images found in this batch"
            echo "has_images=true" >> "$GITHUB_OUTPUT"
          fi
          
          # Debug output
          echo "Content of GITHUB_OUTPUT:"
          cat "$GITHUB_OUTPUT"
          
          echo "folder_name=$folder" >> "$GITHUB_OUTPUT"

      - name: Upload batch artifacts
        if: steps.check-downloads.outputs.has_images == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: batch-${{ matrix.range.prefix }}-${{ matrix.range.start }}-${{ matrix.range.end }}
          path: images_${{ matrix.range.prefix }}_*_${{ matrix.range.start }}_to_${{ matrix.range.end }}
          retention-days: 1
          # Add compression to reduce disk space usage
          compression-level: 9

      - name: Cleanup after upload
        if: always()
        run: |
          rm -rf images_*
          df -h

      - name: Debug outputs
        run: |
          echo "has_images: ${{ steps.check-downloads.outputs.has_images }}"
          echo "folder_name: ${{ steps.check-downloads.outputs.folder_name }}"

  check-artifacts:
    needs: [prepare-matrix, download-batch]
    runs-on: ubuntu-latest
    outputs:
      has_artifacts: ${{ steps.check.outputs.has_artifacts }}
    steps:
      - name: List artifacts
        uses: actions/github-script@v7
        id: check
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            try {
              const [owner, repo] = process.env.GITHUB_REPOSITORY.split('/');
              const artifacts = await github.rest.actions.listArtifactsForRepo({
                owner,
                repo,
                per_page: 100
              });
              
              const hasArtifacts = artifacts.data.artifacts.some(artifact => 
                artifact.name.startsWith('batch-')
              );
              
              console.log(`Repository: ${owner}/${repo}`);
              console.log(`Found artifacts: ${hasArtifacts}`);
              core.setOutput('has_artifacts', hasArtifacts);
            } catch (error) {
              console.error('Error checking artifacts:', error);
              console.error('Repository:', process.env.GITHUB_REPOSITORY);
              core.setOutput('has_artifacts', false);
              if (error.status === 404) {
                console.log('Repository or artifacts not found. Continuing workflow...');
                return;
              }
              throw error;
            }

  commit-changes:
    needs: [prepare-matrix, download-batch, check-artifacts]
    # Only check for actual artifacts
    if: needs.check-artifacts.outputs.has_artifacts == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Clean workspace before checkout
        run: |
          echo "Checking disk space..."
          df -h
          echo "Cleaning up unnecessary files..."
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          df -h

      - name: Minimal checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          sparse-checkout: |
            input/range.json
            empty_ranges.log
            images_*
          sparse-checkout-cone-mode: false
          fetch-depth: 1

      - name: Configure Git for sparse checkout
        run: |
          git config core.sparseCheckout true
          echo "input/range.json" >> .git/info/sparse-checkout
          echo "empty_ranges.log" >> .git/info/sparse-checkout
          echo "images_*" >> .git/info/sparse-checkout
          git config advice.updateSparsePath false

      - name: Download all artifacts
        id: download-artifacts
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          path: ./downloads
          merge-multiple: true

      # Add check after download
      - name: Check for downloaded artifacts
        id: check-artifacts
        run: |
          if [ ! -d "./downloads" ] || [ -z "$(ls -A ./downloads)" ]; then
            echo "No artifacts found to process. Stopping workflow."
            exit 1
          fi

      # Add conditions to remaining steps
      - name: Process and commit changes in batches
        if: steps.check-artifacts.outcome == 'success'
        run: |
          git config user.name "${{ github.repository_owner }}"
          git config user.email "${{ github.repository_owner }}@users.noreply.github.com"

          # Create empty_ranges.log if it doesn't exist
          touch empty_ranges.log
          
          # Add empty range log if no images were found
          if [ "${{ needs.download-batch.outputs.has_images }}" = "false" ]; then
            echo "$(date '+%Y-%m-%d %H:%M:%S') - No images found in range ${{ needs.download-batch.outputs.start_range }} to ${{ needs.download-batch.outputs.end_range }} with prefix ${{ needs.download-batch.outputs.prefix }}" >> empty_ranges.log
          fi

          # Update range.json based on whether images were found
          if [ "${{ needs.download-batch.outputs.has_images }}" = "true" ]; then
            next_start=$((${{ needs.prepare-matrix.outputs.total_end }} + 1))
            next_end=$((${{ needs.prepare-matrix.outputs.total_end }} + 501))
          else
            current_start=${{ needs.prepare-matrix.outputs.total_end }}
            next_start=$((current_start - 501))
            next_end=$current_start
            
            if [ $next_start -lt 1 ]; then
              next_start=1
              next_end=501
            fi
          fi
          
          # Update the path to range.json
          echo "{\"start\": $next_start, \"end\": $next_end}" > input/range.json
          echo "Updated range.json to start=$next_start, end=$next_end"
          
          # Stage range.json with updated path
          git add input/range.json empty_ranges.log

          # Process downloaded files in smaller batches
          if [ -d "./downloads" ] && [ "${{ needs.download-batch.outputs.has_images }}" = "true" ]; then
            # Create a list of files to process
            find ./downloads -type f > files_to_process.txt
            
            # Process files in batches
            batch_size=50
            total_files=$(wc -l < files_to_process.txt)
            current_file=0
            
            while IFS= read -r file; do
              # Check available space
              available_space=$(df -BM / | awk 'NR==2 {print $4}' | sed 's/M//')
              if [ "$available_space" -lt "500" ]; then
                echo "Warning: Low disk space, committing current batch..."
                if ! git diff --staged --quiet; then
                  git commit -m "chore: partial commit of downloaded images (disk space low)"
                  git push
                fi
              fi

              # Get the relative path within downloads directory
              rel_path="${file#./downloads/}"
              target_dir="$(dirname "$rel_path")"
              mkdir -p "$target_dir"
              
              # Move file to target directory
              cp "$file" "$target_dir/"
              rm "$file"
              
              # Stage the moved file with sparse checkout option
              git add --sparse "$target_dir/$(basename "$file")"
              
              # Increment counter and commit if batch size reached
              current_file=$((current_file + 1))
              if [ $((current_file % batch_size)) -eq 0 ]; then
                echo "Processing files $current_file of $total_files"
                if ! git diff --staged --quiet; then
                  git commit -m "chore: batch commit of images ($current_file of $total_files)"
                  git push
                fi
              fi
            done < files_to_process.txt
            
            rm files_to_process.txt
          fi

          # Commit any remaining changes
          if ! git diff --staged --quiet; then
            today=$(date +%Y-%m-%d)
            if [ "${{ needs.download-batch.outputs.has_images }}" = "true" ]; then
              git commit -m "chore: download images for prefix ${{ needs.download-batch.outputs.prefix }} in ${today} from ids ${next_start} to ${next_end}"
            else
              git commit -m "log: no images found in range ${{ needs.download-batch.outputs.start_range }} to ${{ needs.download-batch.outputs.end_range }}, decreasing range to ${next_start}-${next_end}"
            fi
            git push
          fi

      - name: Cleanup
        if: always() && steps.check-artifacts.outcome == 'success'
        run: |
          rm -rf downloads
          rm -rf .git
          df -h

      - name: Delete old artifacts
        if: steps.check-artifacts.outcome == 'success'
        env:
          REPO: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          echo "Fetching artifacts from repository..."
          artifacts=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" "https://api.github.com/repos/$REPO/actions/artifacts" | jq -c '.artifacts[]')

          echo "Filtering artifacts for deletion..."
          for artifact in $artifacts; do
            id=$(echo $artifact | jq -r '.id')
            name=$(echo $artifact | jq -r '.name')
            size=$(echo $artifact | jq -r '.size_in_bytes')
            updated_at=$(echo $artifact | jq -r '.updated_at')
            size_in_gb=$((size / 1024 / 1024 / 1024))

            # Check if artifact is older than 1 day or larger than 3GB
            if [[ "$(date -d "$updated_at" +%s)" -lt "$(date -d '1 day ago' +%s)" || $size_in_gb -gt 3 ]]; then
              echo "Deleting artifact: $name (ID: $id, Size: $size_in_gb GB, Updated: $updated_at)"
              curl -X DELETE -s -H "Authorization: Bearer $GITHUB_TOKEN" "https://api.github.com/repos/$REPO/actions/artifacts/$id"
            fi
          done

      - name: Re-trigger workflow
        if: steps.check-artifacts.outcome == 'success'
        run: |
          # Wait for 1 minutes to allow for system cooldown
          sleep 60
          
          # Trigger the workflow again using GitHub CLI
          gh workflow run organize-images-branches.yml \
            --ref main \
            --repo ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}